# Generated by Django 4.2.6 on 2024-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_comment_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(null=True),
        ),
    ]
