# Generated by Django 4.2.6 on 2024-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_recommendation_user_recommendation_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='users',
            new_name='user',
        ),
    ]
